package aclfmt

import (
	"fmt"
	"io"
	"strings"
	"time"

	"go4.org/netipx"
)

const (
	nginxTemplatePrefix = `%s
geo $remote_addr $is_nyaago_blocklist_ip {
    default 0;
`
	nginxTemplateSuffix = "}\n"
	nginxTemplateEntry  = "    %s 1;\n"
)

type NginxFormatter struct {
	info string
}

func makeNginxFormatter(info string) *NginxFormatter {
	// Make sure info does not contain new line
	if strings.ContainsRune(info, '\n') {
		info = ""
	}
	return &NginxFormatter{
		info: info,
	}
}

func (f *NginxFormatter) Marshal(ipset *netipx.IPSet, w io.Writer) error {
	_, err := fmt.Fprintf(w,
		nginxTemplatePrefix,
		fmt.Sprintf(
			`# Generated by %s
# %s`,
			f.info,
			time.Now().String(),
		))

	if err != nil {
		return fmt.Errorf("write failed: %w", err)
	}

	for _, v := range ipset.Prefixes() {
		_, err = fmt.Fprintf(w, nginxTemplateEntry, v.String())
		if err != nil {
			return fmt.Errorf("write failed: %w", err)
		}
	}

	_, err = fmt.Fprint(w, nginxTemplateSuffix)
	if err != nil {
		return fmt.Errorf("write failed: %w", err)
	}

	return nil
}

func (f *NginxFormatter) Info() string {
	return f.info
}
