package aclfmt

import (
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/HT4w5/nyaago/pkg/dto"
)

const (
	nginxTemplatePrefix = `%s
geo $nyaago_rate_limit {
    default 0;
`
	nginxTemplateSuffix = "}\n"
	nginxTemplateEntry  = "    %s %d;\n" // prefix, ratelimit
)

type NginxFormatter struct {
	info string
}

func makeNginxFormatter(info string) *NginxFormatter {
	// Make sure info does not contain new line
	if strings.ContainsRune(info, '\n') {
		info = ""
	}
	return &NginxFormatter{
		info: info,
	}
}

func (f *NginxFormatter) Marshal(rules []dto.Rule, w io.Writer) error {
	_, err := fmt.Fprintf(w,
		nginxTemplatePrefix,
		fmt.Sprintf(
			`# Generated by %s
# %s`,
			f.info,
			time.Now().Format(time.RFC3339),
		))

	if err != nil {
		return fmt.Errorf("write failed: %w", err)
	}

	for _, v := range rules {
		_, err = fmt.Fprintf(w, nginxTemplateEntry, v.Prefix.String(), v.RateLimit)
		if err != nil {
			return fmt.Errorf("write failed: %w", err)
		}
	}

	_, err = fmt.Fprint(w, nginxTemplateSuffix)
	if err != nil {
		return fmt.Errorf("write failed: %w", err)
	}

	return nil
}

func (f *NginxFormatter) Info() string {
	return f.info
}
